language: python
python:
- 3.8
install:
- pip install .
script:
- pytest -v
deploy:
  provider: pypi
  on:
    distribution: sdist bdist_wheel
    repo: spencerpease/turbo-disco
    tags: true
  user: __token__
  password:
    secure: YRekvE1bUCsePm7p9BS/6lW0glZYeseTLmKBLwDPnhfxCeuL7PNPI+AxL2qsCuLPRzwDvKaWrHgfVlEt9y5tvlwCzAJna0QLrH0xTadBcW8ISpg2TPVncXOZ+pgotIOEpfM7e3Sjv2YEy4jDG25oFgCPzTjBKUjByR8lCxw6g+vKcBjaiCZV+ywfbq3HIywDEOaVRq7HhMNIs3x3FM8h96YY1v+jaBkumlhMVlzpOak6biyu+QRqfbPHPwGou4Ev7hEdj1V8gL7436OUD2ukjrRgTXMDVfHrAgl4ncY2LoWVX1QogOt47u5/DH/VkpqEz9yfOpFrXLxyWzCUJXQlbHZdySw2Q4x5kIMfK15gkdBXCWvd+4JYWyqoSbZm/ZpYDlxZC2eEZmhrygPhnd81nuAafRRFP78Eq0xi93GYq+bRGJ8zQFOv73EuZojBKaMrUizEojbjTAIOG3TMkoI1qD2JFZJt/AzQ1l3nyRL25n1YW5PKK9h/hB2Fzx+4Kr++CjBUhI85Ow4SbdnjEmqmS58o0bnrlYhu0r0RRrSzTwxGQD53/cuL36drXiEdDs6CHIeUxYoWFbctxj7aS5OqlzF/G3xMc6sYB3mdRLZPQGzNzA7t4p7pjlvMixSnUkmQ6fK2VC0BuPGDjPWDbrCiI5QrQ68HBwQm187U5harTOI=
